### ISSUE TITLE
Unable to resolve path for some of the compiled files while building/deploying

### ISSUE THREAD

**Issue by ReadMost** [Tenderly/tenderly-cli#104]
Dear tenderly team, I have found the strange behavior while compiling the files (`tenderly actions build/deploy`).
Context: if we will have just folders in `actions/` dir, then builder will skip these folders while compiling in `out/` dir
To reproduce: 
1) init a new project
2) add any folder in `actions/` dir, e.g. `src/`
3) create an file with action's function, e.g. `actions/src/index.ts`
4) in `tenderly.yaml`
```
sources: actions
    specs:
      example-action-name:
        description: This is just an example, but you can publish this action.
        function: src/index:functionName
```
5) then run `tenderly actions build`
Output: _**Unable to resolve path for some of the compiled files: actions/out/src/index.js
Make sure all imported files are contained in the configured action sources directory (actions).**_

Solution: 
1) create any empty file in `actions/`, e.g. `actions/any.ts`
2) run `tenderly actions build`

Problem in file path resolution while compiling. Builder preserves the folder structure only if other files exist in the same level as folder itself
